version: '3'
services: 
  mongo:
    image: 'mongo'
    container_name: mongo_docker
    environment: 
      - MONGO_INITDB_DATABASE=local
    volumes: 
      - ./data:/data/db
    ports: 
      - '27017:27017'
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    entrypoint: mongod --bind_ip_all